
export {
  AUTO_RANDOM_SPAWN_COUNT_PER_WINDOW,
  AUTO_RANDOM_SPAWN_STRENGTH,
  AUTO_RANDOM_SPAWN_STRENGTH_JITTER,
  AUTO_RANDOM_SPAWN_WIDTH_SCALE,
  AUTO_RANDOM_SPAWN_WINDOW_SEC,
  DECAY_SOFT_TAIL_BASE,
  DEFAULT_BASE_POINT_SIZE,
  DEFAULT_DECAY,
  DEFAULT_DISPLACEMENT_SCALE,
  DEFAULT_POINT_OPACITY,
  DEFAULT_PROPAGATION_SPEED,
  DEFAULT_SIZE_LIFT_SCALE,
  DEFAULT_SWELL_WIDTH,
  DISPLACEMENT_DIR_BIAS_RAD,
  DISP_SOFT_CAP_K,
  FIELD_DELTA_BIAS_STRENGTH,
  FIELD_SIZE_SOFT_CAP_K,
  FIELD_VARIATION_SEED,
  FIELD_WARP_AMPLITUDE,
  FIELD_WARP_FREQUENCY,
  GRID_COLS,
  GRID_JITTER,
  GRID_STAGGER,
  MAX_SWELL_SOURCES,
  POINT_BRIGHTNESS_FROM_FIELD,
  POINT_EDGE_INNER,
  POINT_EDGE_OUTER,
  POINT_SHAPE_ANISOTROPY,
  REST_POINT_SIZE_JITTER,
  STRENGTH_DECAY_PERSISTENCE,
  STRENGTH_TO_WIDTH_SCALE,
  SWELL_BREADTH_STRENGTH_K,
  SWELL_WIDTH_MOD_RANGE,
  SWELL_SHOULDER,
  SWELL_SHOULDER_Z,
  SWELL_WIDE_MIX,
  SWELL_WIDE_WIDTH_SCALE,
  SWELL_WIDTH_TIGHTEN_FLOOR,
  SWELL_WIDTH_TIGHTEN_RATE,
  FOREGROUND_GLOBAL_FIELD_SCALE,
  FOREGROUND_KEY_STRENGTH_JITTER,
  FOREGROUND_KEY_SWELL_MIN_INTERVAL,
  FOREGROUND_KEY_SWELL_STRENGTH,
  FOREGROUND_POINTER_STRENGTH_JITTER,
  FOREGROUND_POINTER_SWELL_STRENGTH,
  FOREGROUND_QUIET_FIELD_SCALE_MUL,
  FOREGROUND_QUIET_OPACITY_MUL,
  FOREGROUND_SAFE_ZONE_BLEND_WORLD,
  FOREGROUND_SAFE_ZONE_INTERIOR_MUL,
  PERF_GRID_COLS_MIN,
  PERF_POINTER_SWELL_MIN_INTERVAL,
  POLISH_DEFAULT_ENABLED,
  POLISH_DEPTH_ATTEN_FLOOR,
  POLISH_DEPTH_CUE_K,
  POLISH_EDGE_OUTER_DELTA,
  POLISH_TONAL_LIFT_K,
  POLISH_VIGNETTE_FLOOR,
  POLISH_VIGNETTE_K,
} from './constants';

export { createPointGridGeometry } from './createPointGridGeometry';

export {
  resolvePerformanceBudget,
  type PerformanceBudget,
  type PerformanceBudgetInput,
  type PerformanceDegradationTier,
} from './resolvePerformanceBudget';

export {
  createRippleFieldMaterial,
  primeShapeUniforms,
  type RippleFieldUniforms,
} from './rippleFieldMaterial';

export { SwellSourceBuffer, type SwellSpawnOptions } from './swellSourceBuffer';

export {
  clientRectToWorldBounds,
  ndcToWorldOrthographic,
  type WorldBounds,
} from './worldFromPointer';
